# mybatis-plus多数据源配置
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        dynamic:
            primary: master #设置默认的数据源或者数据源组,默认值即为master
            strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
            datasource:
                # 主库数据源
                master:
                    type: com.zaxxer.hikari.HikariDataSource
                    driverClassName: com.mysql.cj.jdbc.Driver
                    #url: jdbc:mysql://127.0.0.1:3306/antwalletbot_server?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    url: jdbc:mysql://47.237.23.152:3306/antwalletbot_server?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                    username: root
                    #password: root
                    password: Cy5G*#gY
        hikari:
            # 连接池名
            pool-name: HikariCP
            # 最小空闲连接数
            minimum-idle: 100
            # 最大连接数
            maximum-pool-size: 500
            # 空闲连接超时时间，默认值600000（10分钟）
            idle-timeout: 180000
            # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
            max-lifetime: 900000
            # 连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
            connection-timeout: 30000
            # 用于测试连接是否可用的查询语句
            connection-test-query: SELECT 1


    flyway:
        # 启用或禁用 flyway
        enabled: false
        # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
        clean-disabled: true
        # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
        locations: classpath:db/migration/mysql
        #  metadata 版本控制信息表 默认 flyway_schema_history
        table: flyway_schema_history
        # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
        # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
        baseline-on-migrate: true
        # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
        baseline-version: 0
        # 字符编码 默认 UTF-8
        encoding: UTF-8
        # 是否允许不按顺序迁移 开发建议 true  生产建议 false
        out-of-order: true
        # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
        # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
        # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
        schemas: antwalletbot_server
        # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
        validate-on-migrate: true

